# Generated by Django 6.0.1 on 2026-01-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_student_book_issue_date_book_issued_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
